repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0  # Use the latest version from the pre-commit-hooks repository
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
